# Autogenerated wrapper script for htscodecs_jll for armv6l-linux-musleabihf
export libhtscodecs

using Bzip2_jll
JLLWrappers.@generate_wrapper_header("htscodecs")
JLLWrappers.@declare_library_product(libhtscodecs, "libhtscodecs.so.2")
function __init__()
    JLLWrappers.@generate_init_header(Bzip2_jll)
    JLLWrappers.@init_library_product(
        libhtscodecs,
        "lib/libhtscodecs.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
