# Autogenerated wrapper script for htscodecs_jll for x86_64-apple-darwin
export libhtscodecs

using Bzip2_jll
JLLWrappers.@generate_wrapper_header("htscodecs")
JLLWrappers.@declare_library_product(libhtscodecs, "@rpath/libhtscodecs.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Bzip2_jll)
    JLLWrappers.@init_library_product(
        libhtscodecs,
        "lib/libhtscodecs.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
